-- QUESTION QUERIES

-- 1. #Tickets sold for a particular event
DELIMITER $$
CREATE DEFINER=`root`@`localhost`
PROCEDURE TicketsSold(
IN event_id INT UNSIGNED)
DETERMINISTIC
BEGIN
SELECT SUM(Q_order) as Sum_total FROM ticket
WHERE ticket.event_id = event_id;
END$$
DELIMITER ;
call TicketsSold(13001);


-- 2. Events for which tickets are sold out
SELECT * FROM event
WHERE capacity_left = 0;

 
--  3. #Total Revenue generated by the sale of tickets
DELIMITER $$
CREATE DEFINER=`root`@`localhost`
PROCEDURE RevenueFromAnEvent(
IN event_id INT UNSIGNED)
DETERMINISTIC
BEGIN
SELECT SUM(event.price*Q_order) FROM ticket
    INNER JOIN event ON ticket.event_id = event.event_id
WHERE ticket.event_id = event_id;
END$$
DELIMITER ;
call RevenueFromAnEvent(13001);

SELECT SUM(event.price*Q_order) as tot_rev FROM ticket
    INNER JOIN event ON ticket.event_id = event.event_id
WHERE ticket.event_id = 13001;


-- 4 #Vendors that have applied for participation
SELECT * from vendor;


-- 5 Number of Attendees that have purchased ticket for a particular event
DELIMITER $
CREATE DEFINER=`root`@`localhost`
PROCEDURE NumAttendeesEvent(
IN event_id INT UNSIGNED)
DETERMINISTIC
BEGIN
SELECT SUM(Q_order) AS count FROM ticket
WHERE ticket.event_id = event_id;
END$$
DELIMITER ;
CALL NumAttendeesEvent(13002);


-- 6 Sponsors for a particular event
DELIMITER $
CREATE DEFINER=`root`@`localhost`
PROCEDURE sponsorsEvent(
IN event_id INT UNSIGNED)
DETERMINISTIC
BEGIN
SELECT * FROM sponsors NATURAL JOIN sponsor
WHERE sponsors.event_id = event_id;
END$$
DELIMITER ;
CALL sponsorsEvent(13001);

-- 7. #Events with the Maximum Ticketes Sold
WITH T(event_id,name,tot) AS
(SELECT event.event_id,event.name,SUM(Q_order)
 FROM event NATURAL JOIN ticket
 GROUP BY event.event_id,event.name),
M(max_value) AS
(SELECT MAX(tot) FROM T)
SELECT T.event_id,T.name,T.tot
FROM T,M
WHERE T.tot = M.max_value;
 
-- 8 Ticket Price for a specific event
SELECT price FROM ticket NATURAL JOIN event
WHERE event.event_id = "13001";
 
-- 9 Performers Scheduled to perform at a particular event
DELIMITER $
CREATE DEFINER=`root`@`localhost`
PROCEDURE performersInEvent(
IN event_id INT UNSIGNED)
DETERMINISTIC
BEGIN
SELECT event.event_id,event.name,performer.performer_id,performer.name,performer.genre
FROM performs,performer,event
WHERE performs.performer_id = performer.performer_id
AND event.event_id = performs.event_id
AND event.event_id = event_id;
END$$
DELIMITER ;
CALL performersInEvent(13001);

-- 10. Number of Tickets sold for all events combined
SELECT SUM(Q_order) FROM ticket;


-- 11 Events on a particular Date
SELECT * FROM event
WHERE CAST(event.date_time as DATE) = "2023-03-10";
